#!/bin/sh
# Script de mise a jour des bases rrd et de creation des graphs
# associes.

# $Id: DoUpdate,v 1.4 2005/02/13 10:21:49 toffe Exp $

#set -x

export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin
export LANG=fr_FR@euro

if [ -e /tmp/stop_rrd ]
then
    exit
fi

cd `dirname $0`

for script in $(ls bin/ | grep -v -E '(.pl|inactive)')
do
	cd bin
	sh $script
	cd ..
done
