#!/bin/sh
# Script de mise a jour des bases rrd et de creation des graphs
# associes.

# $Id$

#set -x

export PATH=/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin
export LANG=fr_FR@euro

cd `dirname $0`

for script in $(ls bin/ | grep -v -E '(.pl|inactive)')
do
	cd bin
	sh $script
	cd ..
done
