#! /bin/bash

# $Id$

if [ $# -ne 1 ]
then
	prog=`basename $0`
	echo "usage: $prog <logfile>"
	exit
else
	logfile=$1
fi

delay=60
current=""
logfile_rep=`dirname $logfile`
jaquette_rep="tmp"

while :
do
	date=`date +"%a %d/%m %H:%M"`
	T_title=`dcop amarok player nowPlaying`
	title=`dcop amarok player nowPlaying`
	if test "$T_title" != "$current"
	then
		delay=$(expr `dcop amarok player trackTotalTime` - `dcop amarok player trackCurrentTime `)
		BLOCK_INFO='<div style="{ width:400px; '
		jaquette=`dcop amarok player coverImage`
		if test -s "$jaquette"
		then
		    convert -resize 120x90 "$jaquette" $logfile_rep/$jaquette_rep/`basename "$jaquette"`
		    image="<img src=\"$jaquette_rep/`basename $jaquette`\" style=\"{float: left; clear: left; margin: 0 1em 0 0;}\">"
		    BLOCK_INFO=${BLOCK_INFO}'height:100px; border: dashed 1px #3C63DC; font-weight:bold; background-color:#eee; margin:0px; padding:2px; }" align="left" valign="top">'$image
		else
		    BLOCK_INFO=${BLOCK_INFO}'border: dashed 1px #3C63DC; font-weight:bold; background-color:#eee; margin:0px; padding:2px; }" align="left" valign="top">'
		fi
		album=`dcop amarok player album`
		year=`dcop amarok player year`
		bitrate=`dcop amarok player bitrate`
		BLOCK_INFO=${BLOCK_INFO}"$date - [$album $year] $title ($bitrate) </div>"
		echo $BLOCK_INFO >> $logfile
		current=$T_title
		sleep $delay
	fi
done
