#! /bin/bash

# $Id: xmms-history,v 1.2 2004/10/28 16:13:33 toffe Exp $

if [ $# -ne 1 ]
then
	prog=`basename $0`
	echo "usage: $prog <logfile>"
	exit
else
	logfile=$1
fi

delay=60
current=""

while :
do
	date=`date +"%a %d/%m %H:%M"`
	T_title=`xmms-shell -e status | head -1 | sed -e 's/Playing: //' -e 's/([^(]*)$//'`
	title=`xmms-shell -e status | awk '/Playing:/ { print substr($0,10) }'`
	if test "$T_title" != "$current"
	then
		echo "$date - $title" >> $logfile
		current=$T_title
	fi
	sleep $delay
done
