#!/bin/bash
#
# Make Iso file from a directory.
#
# $Id: burnDir2ISO,v 1.1 2004/03/24 15:28:00 toffe Exp $

TITRE=$1
REP=/home/toffe/a_graver/

/usr/bin/mkisofs -R -r -J --hide-rr-moved -V "$TITRE" -o $REP$TITRE.iso $REP
