#!/bin/sh
# Remove frozen mails from queue

# $Id: DelFrozen,v 1.2 2004/05/01 08:02:46 toffe Exp $

FROZEN_COUNT=`mailq | grep -c -E '<.*>.*frozen'`
echo "Going to remove $FROZEN_COUNT mail(s) in 5 seconds"
sleep 5
exim -bpu | awk '/\*\*\* frozen \*\*\*/ {print $3}' | xargs exim -Mrm
