#!/bin/bash

# $Id$

SOURCE=$1
DESTINATION=NewEncoding_${SOURCE}

mencoder -oac mp3lame \
         -lameopts preset=medium \
	 -ovc xvid \
	 -xvidencopts bitrate=687000:vhq=3 \
	 $SOURCE \
	 -o $DESTINATION
