#!/bin/bash

# $Id: EncodePerso,v 1.3 2006-12-08 20:43:55 toffe Exp $

SOURCE=$1
DESTINATION=NewEncoding_${SOURCE}

mencoder -oac mp3lame \
         -lameopts preset=medium \
	 -ovc xvid \
	 -xvidencopts bitrate=687000:vhq=3 \
	 $SOURCE \
	 -o $DESTINATION
