#!/bin/sh
#
# $Id$
#
# Script de generation automatique des pages de stats par virtual hosts
#

echo "`date` : Generation de statistiques web"

for conf_file in /opt/tools/scripts/conf/*.conf
do
	F=`basename $conf_file .conf`
	echo "`date +%T`: $F"
	/usr/local/sbin/webalizer -c $conf_file 2>&1 > /opt/tools/scripts/${F}_wbr
done
echo "`date +%T`: Termine"
