#!/bin/sh
#
# Script de generation automatique des pages de stats par virtual hosts
#

echo "`date` : Generation de statistiques web"

for conf_file in /opt/tools/scripts/conf/*.conf
do
	echo "`date +%T`: `basename $conf_file .conf`"
	/usr/local/sbin/webalizer -c $conf_file 2>&1 > /opt/tools/scripts/`basename $conf_file .conf`_wbr
done
echo "`date +%T`: Termine"
